spring:
   datasource:
       url: jdbc:mysql://localhost:3306/myapp
       username: root
       password:  
       type: com.alibaba.druid.pool.DruidDataSource
       driver-class-name: com.mysql.jdbc.Driver
   mvc:
     view:
       prefix: /webapp/static/
       suffix: .jsp
   redis:
       host: localhost
mybatis:
   mapper-locations: classpath*:com/cn/ask/mapping/*.xml
   type-aliases-package: com.cn.ask.model
pagehelper:
   helperDialect: mysql
   reasonable: true
   supportMethodsArguments: true
   params: count=countSql
