logging:

#日志配置部分还没搞明白，这部分配置没生效。

   path: /home/logs
   file: ask.log
   level:
       root: info
spring:
   datasource:
       url: jdbc:mysql://localhost:3306/myapp
       username: root
       password: 
       type: com.alibaba.druid.pool.DruidDataSource
       driver-class-name: com.mysql.jdbc.Driver
   mvc:
     view:
       prefix: /webapp/static/
       suffix: .jsp
mybatis:
  #*Mapper.java可以随便放，只要和mapper.xml对应上就行
   mapper-locations: classpath*:com/cn/ask/mapping/*.xml
   type-aliases-package: com.cn.ask.model

#这个插件是mybatis的分页查询

pagehelper:
   helperDialect: mysql
   reasonable: true
   supportMethodsArguments: true
   params: count=countSql
